name: pluto_grid_export
description: PlutoGridExport converts PlutoGrid's metadata to CSV or PDF. Used with PlutoGrid.
version: 1.0.2
homepage: https://bosskmk.github.io
repository: https://github.com/bosskmk/pluto_grid/tree/master/packages/pluto_grid_export
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
#  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  pluto_grid:
    path: ../..
  csv: ^5.1.1
  pdf: ^3.10.6
  printing: ^5.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.3
  build_runner: ^2.4.6
  flutter_lints: ^3.0.1
